name: Scrape fuels

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - run: pip install requests pandas yfinance

      - run: python scrape_fuels.py

      - run: ls -l

      - name: Commit
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add *.csv || true

          if ! git diff --cached --quiet; then
            git commit -m "Update fuel prices"
            git push
          else
            echo "No changes"
          fi
